"""Added certificates table

Revision ID: a82db9b253e1
Revises: 
Create Date: 2017-05-18 22:26:04.322490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82db9b253e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('command_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

























    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###



























    op.drop_table('command_sequences')

    # ### end Alembic commands ###
