SQLALCHEMY_DATABASE_URI = 'sqlite:///scep.db'
SQLALCHEMY_DATABASE_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = False

SCEP_CA_CN = 'COMMANDMENT-SCEPCA'
SCEP_CA_O = 'Commandment Inc'
SCEP_CA_C = 'AU'

SCEP_CHALLENGE = 'sekret'
CA_ROOT = '/tmp/ca'

FORCE_DEGENERATE_FOR_SINGLE_CERT = False
