"""create available_os_updates table

Revision ID: 6675e981817e
Revises: 70ff84113e8f
Create Date: 2017-06-23 17:40:11.879267

"""
from alembic import op, context
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6675e981817e'
down_revision = '70ff84113e8f'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_os_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('allows_install_later', sa.Boolean(), nullable=True),
    sa.Column('app_identifiers_to_close', commandment.dbtypes.JSONEncodedDict(), nullable=True),
    sa.Column('human_readable_name', sa.String(), nullable=True),
    sa.Column('human_readable_name_locale', sa.String(), nullable=True),
    sa.Column('is_config_data_update', sa.Boolean(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('is_firmware_update', sa.Boolean(), nullable=True),
    sa.Column('metadata_url', sa.String(), nullable=True),
    sa.Column('product_key', sa.String(), nullable=True),
    sa.Column('restart_required', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def schema_downgrades():
    """schema downgrade migrations go here."""
    op.drop_table('available_os_updates')


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
